from collections import defaultdict

from fastapi import APIRouter, Query
from app.services.supabase_client import get_client

router = APIRouter()


def _attach_sentiment_summary(client, docs: list[dict]) -> list[dict]:
    """Mutates docs in place, adding avg_sentiment_score / sentiment_label
    (majority vote) / risk_count, computed from extraction_results. Used by
    the dashboard cards so a visitor sees signal without clicking into every
    document."""
    doc_ids = [d["id"] for d in docs]
    if not doc_ids:
        return docs

    chunk_rows = (
        client.table("chunks").select("id, document_id").in_("document_id", doc_ids).execute().data
    )
    chunk_to_doc = {c["id"]: c["document_id"] for c in chunk_rows}
    chunk_ids = list(chunk_to_doc.keys())

    extractions = (
        client.table("extraction_results")
        .select("chunk_id, sentiment_label, sentiment_score, risk_flags")
        .in_("chunk_id", chunk_ids)
        .execute()
        .data
        if chunk_ids
        else []
    )

    agg = defaultdict(lambda: {"scores": [], "labels": [], "risk_count": 0})
    for e in extractions:
        doc_id = chunk_to_doc.get(e["chunk_id"])
        if not doc_id:
            continue
        if e.get("sentiment_score") is not None:
            agg[doc_id]["scores"].append(float(e["sentiment_score"]))
        if e.get("sentiment_label"):
            agg[doc_id]["labels"].append(e["sentiment_label"])
        agg[doc_id]["risk_count"] += len(e.get("risk_flags") or [])

    for d in docs:
        a = agg.get(d["id"])
        if a and a["scores"]:
            d["avg_sentiment_score"] = round(sum(a["scores"]) / len(a["scores"]), 3)
            d["sentiment_label"] = max(set(a["labels"]), key=a["labels"].count) if a["labels"] else None
            d["risk_count"] = a["risk_count"]
        else:
            d["avg_sentiment_score"] = None
            d["sentiment_label"] = None
            d["risk_count"] = 0
    return docs


@router.get("/")
def list_documents(market: str | None = Query(default=None)):
    client = get_client()
    q = client.table("documents").select("*")
    if market:
        q = q.eq("market", market)
    docs = q.execute().data
    return _attach_sentiment_summary(client, docs)


@router.get("/metrics")
def get_metrics():
    """Serves the precomputed benchmark evaluation results
    (benchmark/metrics.json), generated by scripts/evaluate.py.

    NOTE: this route must stay registered before GET /{document_id} --
    otherwise FastAPI matches "/metrics" against the /{document_id} pattern
    first (document_id="metrics"), which 500s trying to query a document by
    the literal id "metrics". Bit us in production; keep this route first.
    """
    import json
    import os

    path = os.path.join(os.path.dirname(__file__), "..", "..", "..", "benchmark", "metrics.json")
    if not os.path.exists(path):
        return {"status": "not_computed_yet"}
    with open(path) as f:
        return json.load(f)


@router.get("/metrics/retrieval")
def get_retrieval_metrics():
    """Serves benchmark/retrieval_metrics.json (scripts/evaluate_retrieval.py).
    Also registered before /{document_id} for the same shadowing reason as
    /metrics above -- FastAPI matches routes in registration order, and
    /{document_id} would otherwise swallow this."""
    import json
    import os

    path = os.path.join(os.path.dirname(__file__), "..", "..", "..", "benchmark", "retrieval_metrics.json")
    if not os.path.exists(path):
        return {"status": "not_computed_yet"}
    with open(path) as f:
        return json.load(f)


@router.get("/risks-topics")
def get_risks_topics():
    """Aggregates every risk flag and topic across all extraction_results,
    with the source company/ticker/market attached, for the /risks index
    page. Also registered before /{document_id} for the same shadowing
    reason as the /metrics routes above."""
    client = get_client()

    docs = client.table("documents").select("id, company, ticker, market").execute().data
    doc_by_id = {d["id"]: d for d in docs}

    chunk_rows = client.table("chunks").select("id, document_id").execute().data
    chunk_to_doc = {c["id"]: c["document_id"] for c in chunk_rows}

    extractions = (
        client.table("extraction_results")
        .select("chunk_id, risk_flags, topics")
        .execute()
        .data
    )

    risks = []
    topic_companies = defaultdict(set)

    for e in extractions:
        doc_id = chunk_to_doc.get(e["chunk_id"])
        doc = doc_by_id.get(doc_id)
        if not doc:
            continue
        for flag in e.get("risk_flags") or []:
            risks.append(
                {
                    "flag": flag,
                    "company": doc["company"],
                    "ticker": doc["ticker"],
                    "market": doc["market"],
                    "document_id": doc_id,
                }
            )
        for topic in e.get("topics") or []:
            topic_companies[topic].add(f"{doc['ticker']}|{doc['market']}")

    topics = [
        {
            "topic": topic,
            "count": len(companies),
            "companies": sorted(companies),
        }
        for topic, companies in topic_companies.items()
    ]
    topics.sort(key=lambda t: t["count"], reverse=True)

    return {"risks": risks, "topics": topics}


@router.get("/{document_id}")
def get_document(document_id: str):
    client = get_client()
    resp = client.table("documents").select("*").eq("id", document_id).single().execute()
    return resp.data


@router.get("/{document_id}/extractions")
def get_extractions(document_id: str):
    """Returns extraction_results rows for this document, each with the
    underlying chunk's text/index embedded -- so the frontend can show the
    source excerpt behind each sentiment/risk/topic call, not just the
    model's summary of it."""
    client = get_client()
    chunk_rows = (
        client.table("chunks")
        .select("id, chunk_index")
        .eq("document_id", document_id)
        .execute()
        .data
    )
    ids = [c["id"] for c in chunk_rows]
    if not ids:
        return []
    resp = (
        client.table("extraction_results")
        .select("*, chunks(chunk_index, text)")
        .in_("chunk_id", ids)
        .execute()
    )
    # order by chunk_index so the frontend renders in document order, not insertion order
    return sorted(resp.data, key=lambda r: r.get("chunks", {}).get("chunk_index", 0))


@router.get("/{document_id}/financials")
def get_financials(document_id: str):
    """Returns the financial_snapshots row for this document, if any
    (scripts/extract_financials.py). Null fields mean the figure wasn't
    explicitly disclosed in the collected transcript excerpt, not zero."""
    client = get_client()
    resp = (
        client.table("financial_snapshots")
        .select("*")
        .eq("document_id", document_id)
        .execute()
    )
    return resp.data[0] if resp.data else None
