from fastapi import APIRouter, Query
from app.services.supabase_client import get_client

router = APIRouter()


@router.get("/")
def list_documents(market: str | None = Query(default=None)):
    client = get_client()
    q = client.table("documents").select("*")
    if market:
        q = q.eq("market", market)
    resp = q.execute()
    return resp.data


@router.get("/metrics")
def get_metrics():
    """Serves the precomputed benchmark evaluation results
    (benchmark/metrics.json), generated by scripts/evaluate.py.

    NOTE: this route must stay registered before GET /{document_id} --
    otherwise FastAPI matches "/metrics" against the /{document_id} pattern
    first (document_id="metrics"), which 500s trying to query a document by
    the literal id "metrics". Bit us in production; keep this route first.
    """
    import json
    import os

    path = os.path.join(os.path.dirname(__file__), "..", "..", "..", "benchmark", "metrics.json")
    if not os.path.exists(path):
        return {"status": "not_computed_yet"}
    with open(path) as f:
        return json.load(f)


@router.get("/{document_id}")
def get_document(document_id: str):
    client = get_client()
    resp = client.table("documents").select("*").eq("id", document_id).single().execute()
    return resp.data


@router.get("/{document_id}/extractions")
def get_extractions(document_id: str):
    """Returns extraction_results rows for this document, each with the
    underlying chunk's text/index embedded -- so the frontend can show the
    source excerpt behind each sentiment/risk/topic call, not just the
    model's summary of it."""
    client = get_client()
    chunk_rows = (
        client.table("chunks")
        .select("id, chunk_index")
        .eq("document_id", document_id)
        .execute()
        .data
    )
    ids = [c["id"] for c in chunk_rows]
    if not ids:
        return []
    resp = (
        client.table("extraction_results")
        .select("*, chunks(chunk_index, text)")
        .in_("chunk_id", ids)
        .execute()
    )
    # order by chunk_index so the frontend renders in document order, not insertion order
    return sorted(resp.data, key=lambda r: r.get("chunks", {}).get("chunk_index", 0))
