from fastapi import APIRouter, Query
from app.services.supabase_client import get_client

router = APIRouter()


@router.get("/")
def list_documents(market: str | None = Query(default=None)):
    client = get_client()
    q = client.table("documents").select("*")
    if market:
        q = q.eq("market", market)
    resp = q.execute()
    return resp.data


@router.get("/{document_id}/extractions")
def get_extractions(document_id: str):
    client = get_client()
    chunk_ids = (
        client.table("chunks")
        .select("id")
        .eq("document_id", document_id)
        .execute()
        .data
    )
    ids = [c["id"] for c in chunk_ids]
    if not ids:
        return []
    resp = (
        client.table("extraction_results")
        .select("*")
        .in_("chunk_id", ids)
        .execute()
    )
    return resp.data


@router.get("/metrics")
def get_metrics():
    """Serves the precomputed benchmark evaluation results
    (benchmark/metrics.json), generated by scripts/evaluate.py."""
    import json
    import os

    path = os.path.join(os.path.dirname(__file__), "..", "..", "..", "benchmark", "metrics.json")
    if not os.path.exists(path):
        return {"status": "not_computed_yet"}
    with open(path) as f:
        return json.load(f)
