"""
Retrieval quality + latency evaluation, per docs/METHODOLOGY.md §A.3/A.5.

METHOD NOTE (read before trusting these numbers): a real relevance-judged
query set (a human writing queries and marking which chunks are actually
relevant) doesn't exist for this pilot -- same honesty issue as the gold
sentiment labels. Rather than skip retrieval eval entirely or fabricate
relevance judgments, this uses a standard, disclosed self-retrieval proxy:
each chunk's own extraction_results.summary (already generated by Groq
during scripts/run_extraction.py) is used as a synthetic query, and we check
whether querying that summary actually retrieves the chunk it summarizes.
This is a real, if narrower, signal -- it answers "if you ask about what's
IN a chunk, does the pipeline find that chunk," which exercises the same
embedding+pgvector path chat queries use, but it is NOT equivalent to a
human-curated relevance benchmark and shouldn't be reported as one.

Computes, segmented by market:
  - Recall@k for k in (1, 3, 5, 10): fraction of synthetic queries whose
    source chunk appears in the top-k retrieved results
  - MRR: mean reciprocal rank of the source chunk (0 if not retrieved
    within top match_count)
  - Latency: mean + p95 wall-clock ms per query (embed_text call + the
    match_chunks RPC combined, i.e. what retrieve_top_k actually costs)

Usage:
    python scripts/evaluate_retrieval.py
Output:
    benchmark/retrieval_metrics.json
"""
import json
import statistics
import sys
import time
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend"))

from app.services.gemini_service import embed_text  # noqa: E402
from app.services.supabase_client import get_client  # noqa: E402

OUT_PATH = Path(__file__).resolve().parent.parent / "benchmark" / "retrieval_metrics.json"
MATCH_COUNT = 10
K_VALUES = [1, 3, 5, 10]


def main():
    client = get_client()

    rows = (
        client.table("extraction_results")
        .select("chunk_id, summary, chunks(document_id, documents(market))")
        .execute()
        .data
    )
    queries = [r for r in rows if r.get("summary")]
    print(f"{len(rows)} extraction_results rows, {len(queries)} have a summary to use as a synthetic query.")

    by_market = defaultdict(lambda: {"ranks": [], "latencies_ms": []})

    for i, row in enumerate(queries, 1):
        chunk_id = row["chunk_id"]
        market = row["chunks"]["documents"]["market"]
        query_text = row["summary"]

        t0 = time.perf_counter()
        query_embedding = embed_text(query_text, task_type="retrieval_query")
        resp = client.rpc(
            "match_chunks", {"query_embedding": query_embedding, "match_count": MATCH_COUNT}
        ).execute()
        elapsed_ms = (time.perf_counter() - t0) * 1000

        retrieved_ids = [r["chunk_id"] for r in (resp.data or [])]
        rank = retrieved_ids.index(chunk_id) + 1 if chunk_id in retrieved_ids else None

        by_market[market]["ranks"].append(rank)
        by_market[market]["latencies_ms"].append(elapsed_ms)
        print(f"  [{i}/{len(queries)}] {market}: rank={rank} ({elapsed_ms:.0f}ms)")

    results = {"method": "self_retrieval_proxy_not_human_relevance_judgments", "match_count": MATCH_COUNT}

    for market, data in by_market.items():
        ranks = data["ranks"]
        n = len(ranks)
        recall_at_k = {
            f"recall@{k}": sum(1 for r in ranks if r is not None and r <= k) / n for k in K_VALUES
        }
        mrr = sum((1 / r) if r is not None else 0.0 for r in ranks) / n
        lat = sorted(data["latencies_ms"])
        p95_idx = min(int(len(lat) * 0.95), len(lat) - 1)
        results[market] = {
            "n": n,
            **recall_at_k,
            "mrr": mrr,
            "latency_ms_mean": statistics.mean(lat),
            "latency_ms_p95": lat[p95_idx],
        }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(results, f, indent=2)

    print(json.dumps(results, indent=2))
    print(f"\nWrote {OUT_PATH}")


if __name__ == "__main__":
    main()
